# Generated by Django 6.0.2 on 2026-02-04 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('cardio', 'Cardio'), ('fuerza', 'Fuerza'), ('hipertrofia', 'Hipertrofia')], max_length=20)),
                ('descripcion', models.TextField()),
                ('creada', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
