# Generated by Django 6.0.2 on 2026-02-08 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrenamientos', '0002_rutina_usuario_alter_rutina_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutina',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='rutinas/'),
        ),
    ]
